'use client';
import {useEffect,useState} from 'react';
import {Flame,ArrowRight,LockKeyhole,Check,Eye,EyeOff,LogOut,HardDrive,MonitorDown,Smartphone,MailCheck,Users} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import Communication from './communication';
import {currentUser,register,login,verifyEmail,resendVerification,logout,updateAccount,usernameAvailable,usernameError,type LocalUser} from '@/lib/online';
function errorText(e:unknown){return e instanceof Error?e.message:'Something went wrong. Please try again.';}
const WINDOWS_APP='https://github.com/kurosakijin/Aemeath/releases/latest/download/Aemeath-Windows.exe';
const ANDROID_APP='https://github.com/kurosakijin/Aemeath/releases/latest/download/Aemeath-Android.apk';
type PublicInvite={code:string;expires:number;id:string;name:string;icon?:string;banner?:string;inviter:string;members:number};
function AppDownloads({compact=false}:{compact?:boolean}){return <div className={compact?'app-downloads compact':'app-downloads'} aria-label="Download Aemeath apps"><span className="app-download-title">Get the app</span><a href={WINDOWS_APP} title="Download Aemeath for Windows"><MonitorDown size={compact?17:19}/><span>Windows</span></a><a href={ANDROID_APP} title="Download Aemeath for Android"><Smartphone size={compact?17:19}/><span>Android</span></a></div>}
export function UsernameField({value,onChange,excludeId,disabled}:{value:string;onChange:(v:string)=>void;excludeId?:string;disabled:boolean}){
 const [status,setStatus]=useState('');const [valid,setValid]=useState(false);
 useEffect(()=>{let alive=true;setValid(false);if(!value){setStatus('3–24 letters, numbers, or underscores.');return;}const problem=usernameError(value);if(problem){setStatus(problem);return;}setStatus('Checking availability…');const timer=setTimeout(()=>{usernameAvailable(value,excludeId).then(available=>{if(alive){setStatus(available?'Username is available.':'That username already exists.');setValid(available);}}).catch(e=>{if(alive)setStatus(errorText(e))});},250);return()=>{alive=false;clearTimeout(timer)};},[value,excludeId]);
 return <div className="account-field"><label htmlFor="account-username">Username</label><input id="account-username" autoComplete="username" value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} minLength={3} maxLength={24} pattern="[A-Za-z0-9_]{3,24}" placeholder="Your unique name" required aria-describedby="username-status"/><p id="username-status" className={'field-hint '+(valid?'available':'')} role="status">{valid&&<Check size={13}/>} {status}</p></div>
}
function PasswordField({label='Password',value,onChange,newPassword=false,optional=false,disabled=false}:{label?:string;value:string;onChange:(v:string)=>void;newPassword?:boolean;optional?:boolean;disabled?:boolean}){const [visible,setVisible]=useState(false);const id=label.toLowerCase().replaceAll(' ','-');return <div className="account-field"><label htmlFor={id}>{label}{optional&&<span className="optional"> · optional</span>}</label><div className="password-input"><input id={id} type={visible?'text':'password'} autoComplete={newPassword?'new-password':'current-password'} value={value} onChange={e=>onChange(e.target.value)} minLength={newPassword?8:undefined} maxLength={128} required={!optional} disabled={disabled} placeholder={newPassword?'At least 8 characters':'Enter your password'}/><button type="button" aria-label={(visible?'Hide ':'Show ')+label.toLowerCase()} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>}
export function AccountSettings({user,onSaved,onLogout,onClose}:{user:LocalUser;onSaved:(u:LocalUser)=>void;onLogout:()=>void;onClose:()=>void}){
 const [username,setUsername]=useState(user.name),[email,setEmail]=useState(user.email),[password,setPassword]=useState(''),[nextPassword,setNextPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{const u=await updateAccount(username,email,password,nextPassword);onSaved(u);setPassword('');setNextPassword('');setSaved(true);}catch(e){setError(errorText(e));}finally{setBusy(false)}}
 return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose()}}><DialogContent className="aemeath-dialog account-settings"><DialogTitle>Account settings</DialogTitle><DialogDescription>Your name, your details, your little corner.</DialogDescription><form onSubmit={save} className="account-form"><UsernameField value={username} onChange={v=>{setUsername(v);setSaved(false)}} excludeId={user.id} disabled={busy}/><div className="account-field"><label htmlFor="settings-email">Email</label><input id="settings-email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>{setEmail(e.target.value);setSaved(false)}} disabled={busy}/></div><div className="settings-rule"/><PasswordField label="Current password" value={password} onChange={setPassword} disabled={busy}/><PasswordField label="New password" value={nextPassword} onChange={v=>{setNextPassword(v);setSaved(false)}} newPassword optional disabled={busy}/><p className="field-hint">Enter your current password to save changes. Leave the new password blank to keep it.</p>{error&&<p className="account-error" role="alert">{error}</p>}{saved&&<p className="saved-message" role="status"><Check size={16}/> Account updated.</p>}<button className="primary" disabled={busy} type="submit">{busy?'Saving changes…':'Save changes'}<Check size={17}/></button></form><div className="settings-footer"><span><HardDrive size={14}/> Synced to your account</span><button disabled={busy} onClick={onLogout}><LogOut size={15}/> Log out</button></div></DialogContent></Dialog>
}
export default function AccountGate(){
 const [user,setUser]=useState<LocalUser|null>(null),[ready,setReady]=useState(false),[mode,setMode]=useState('login'),[username,setUsername]=useState(''),[email,setEmail]=useState(''),[identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[settings,setSettings]=useState(false),[verification,setVerification]=useState<{id:string;email:string;purpose:'register'|'login'}|null>(null),[code,setCode]=useState(''),[resent,setResent]=useState(false),[invite,setInvite]=useState<PublicInvite|null>(null),[inviteLoading,setInviteLoading]=useState(false),[inviteError,setInviteError]=useState('');
 useEffect(()=>{currentUser().then(setUser).catch(e=>setError(errorText(e))).finally(()=>setReady(true));const refresh=()=>{currentUser().then(setUser).catch(e=>setError(errorText(e)))};const channel=typeof BroadcastChannel!=='undefined'?new BroadcastChannel('aemeath-accounts'):null;if(channel)channel.onmessage=refresh;window.addEventListener('focus',refresh);window.addEventListener('aemeath-session-expired',refresh);return()=>{channel?.close();window.removeEventListener('focus',refresh);window.removeEventListener('aemeath-session-expired',refresh)};},[]);
 useEffect(()=>{const inviteCode=new URLSearchParams(window.location.search).get('invite');if(!inviteCode)return;setMode('register');setInviteLoading(true);fetch('/api/chat?invite='+encodeURIComponent(inviteCode),{cache:'no-store'}).then(async response=>{const data=await response.json() as {error?:string;invite?:PublicInvite};if(!response.ok||!data.invite)throw new Error(data.error||'This invitation is unavailable.');setInvite(data.invite)}).catch(e=>setInviteError(errorText(e))).finally(()=>setInviteLoading(false))},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=mode==='register'?await register(username,email,password):await login(identifier,password);if(result.verification){setVerification(result.verification);setCode('');setPassword('');return}if(result.user){setUser(result.user);setPassword('');setUsername('');setEmail('');setIdentifier('')}}catch(e){setError(errorText(e));}finally{setBusy(false)}}
 async function confirmCode(e:React.FormEvent){e.preventDefault();if(!verification||busy)return;setBusy(true);setError('');try{setUser(await verifyEmail(verification.id,code));setVerification(null);setCode('');setPassword('');setUsername('');setEmail('');setIdentifier('')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function resend(){if(!verification||busy)return;setBusy(true);setError('');setResent(false);try{await resendVerification(verification.id);setResent(true)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function leave(){try{await logout();setUser(null);setSettings(false);setPassword('');setError('');setMode('login');}catch(e){setError(errorText(e));setUser(null);setSettings(false)}}
 if(!ready)return <main className="account-loading"><Flame size={28}/><p>Opening Aemeath…</p></main>;
 if(user)return <><Communication key={user.id} user={user} onSettings={()=>setSettings(true)}/>{settings&&<AccountSettings user={user} onSaved={setUser} onClose={()=>setSettings(false)} onLogout={leave}/>}</>;
 if(verification)return <main className="auth-page"><section className="auth-story"><a className="auth-brand" href="/"><Flame size={27}/><span>aemeath</span></a><div className="auth-story-copy"><span className="eyebrow">ONE MORE STEP.</span><h1>Check your email.<br/>Keep your corner safe.</h1><p>Every account and every login is confirmed<br/>with a short-lived verification code.</p><div className="auth-lines"><span/><span/><span/></div></div></section><section className="auth-main"><div className="auth-card verification-card"><div className="auth-mobile-brand"><Flame size={25}/> aemeath</div><span className="auth-lock"><MailCheck size={23}/></span><h2>Enter your code.</h2><p className="auth-subtitle">We sent a six-digit code to <strong>{verification.email}</strong>. It expires in 10 minutes.</p><form className="account-form" onSubmit={confirmCode}><div className="account-field"><label htmlFor="verification-code">Verification code</label><input id="verification-code" className="verification-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} autoFocus required placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} disabled={busy}/></div>{error&&<p className="account-error" role="alert">{error}</p>}{resent&&<p className="saved-message" role="status"><Check size={16}/> A new code was sent.</p>}<button type="submit" className="primary auth-submit" disabled={busy||code.length!==6}>{busy?'Verifying…':'Verify and continue'}<ArrowRight size={18}/></button></form><p className="auth-switch">Didn’t receive it? <button type="button" disabled={busy} onClick={()=>void resend()}>Send another code</button></p><button className="verification-back" disabled={busy} onClick={()=>{setVerification(null);setCode('');setError('');setResent(false)}}>← Back to {verification.purpose==='login'?'login':'registration'}</button></div></section></main>;
 if(inviteLoading||invite||inviteError)return <main className="public-invite-page" style={{"--public-invite-banner":invite?.banner||'#783b91'} as React.CSSProperties}><a className="public-invite-brand" href="/"><Flame size={27}/><span>aemeath</span></a><section className="public-invite-card">{inviteLoading?<div className="public-invite-loading"><Flame size={30}/><p>Opening your invitation…</p></div>:<><div className="public-invite-heading"><div className="public-invite-icon">{invite?.icon?<img src={invite.icon} alt=""/>:(invite?.name||'A').slice(0,2).toUpperCase()}</div>{invite?<><p><strong>{invite.inviter}</strong> invited you to join</p><h1>{invite.name}</h1><span><i/><Users size={14}/>{invite.members} member{Number(invite.members)===1?'':'s'}</span></>:<><h1>Invitation unavailable</h1><p>{inviteError}</p></>}</div>{invite&&<div className="public-invite-form"><h2>{mode==='register'?'Create your account':'Welcome back'}</h2><p>{mode==='register'?'Join the conversation in a few moments.':'Log in to accept this invitation.'}</p><form className="account-form" onSubmit={submit}>{mode==='register'?<><UsernameField value={username} onChange={setUsername} disabled={busy}/><div className="account-field"><label htmlFor="invite-register-email">Email</label><input id="invite-register-email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></div></>:<div className="account-field"><label htmlFor="invite-login-identifier">Username or email</label><input id="invite-login-identifier" autoComplete="username" required maxLength={254} placeholder="Enter your username or email" value={identifier} onChange={e=>setIdentifier(e.target.value)} disabled={busy}/></div>}<PasswordField key={'invite-'+mode} value={password} onChange={setPassword} newPassword={mode==='register'} disabled={busy}/>{error&&<p className="account-error" role="alert">{error}</p>}<button type="submit" className="primary auth-submit" disabled={busy}>{busy?(mode==='register'?'Creating your account…':'Logging in…'):(mode==='register'?'Create account':'Log in')}<ArrowRight size={18}/></button></form><p className="auth-switch">{mode==='login'?'New to Aemeath?':'Already have an account?'} <button disabled={busy} onClick={()=>{setMode(mode==='login'?'register':'login');setError('');setPassword('')}}>{mode==='login'?'Create account':'Log in'}</button></p></div>}</>}</section></main>;
 return <main className="auth-page"><section className="auth-story"><a className="auth-brand" href="/"><Flame size={27}/><span>aemeath</span></a><div className="auth-story-copy"><span className="eyebrow">YOUR PEOPLE. YOUR PLACE.</span><h1>A familiar place.<br/>A fresh start.</h1><p>A small corner for conversations,<br/>connections, and everything in between.</p><div className="auth-lines"><span/><span/><span/></div></div><div className="auth-local-note"><HardDrive size={17}/><span>Your conversations, anywhere<br/><small>Sign in from any of your devices.</small></span></div></section><section className="auth-main"><div className="auth-card"><div className="auth-mobile-brand"><Flame size={25}/> aemeath</div><span className="auth-lock"><LockKeyhole size={23}/></span><h2>{mode==='login'?'Welcome back.':'Make yourself at home.'}</h2><p className="auth-subtitle">{mode==='login'?'Your corner of the internet is waiting.':'Just three things to get started.'}</p><Tabs value={mode} onValueChange={v=>{if(!busy){setMode(v);setError('');setPassword('')}}}><TabsList className="auth-tabs"><TabsTrigger value="login" disabled={busy}>Log in</TabsTrigger><TabsTrigger value="register" disabled={busy}>Create account</TabsTrigger></TabsList></Tabs><form className="account-form" onSubmit={submit}>{mode==='register'?<><UsernameField value={username} onChange={setUsername} disabled={busy}/><div className="account-field"><label htmlFor="register-email">Email</label><input id="register-email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></div></>:<div className="account-field"><label htmlFor="login-identifier">Username or email</label><input id="login-identifier" autoComplete="username" required maxLength={254} placeholder="Enter your username or email" value={identifier} onChange={e=>setIdentifier(e.target.value)} disabled={busy}/></div>}<PasswordField key={mode} value={password} onChange={setPassword} newPassword={mode==='register'} disabled={busy}/>{error&&<p className="account-error" role="alert">{error}</p>}<button type="submit" className="primary auth-submit" disabled={busy}>{busy?(mode==='register'?'Creating your account…':'Logging in…'):(mode==='register'?'Create account':'Log in')}<ArrowRight size={18}/></button></form><p className="auth-switch">{mode==='login'?'New around here?':'Already have an account?'} <button disabled={busy} onClick={()=>{setMode(mode==='login'?'register':'login');setError('');setPassword('')}}>{mode==='login'?'Create an account':'Log in'}</button></p><AppDownloads/><div className="auth-storage"><HardDrive size={15}/><p>Create an online account to message and call. Earlier browser-only prototype accounts are separate.</p></div></div><footer className="auth-footer">A little closer. A little more you.</footer></section></main>
}
