"use client";
import {Download,ExternalLink,EyeOff,X,ZoomIn,ZoomOut} from "lucide-react";
import {useCallback,useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";

export default function ImagePreview({src,spoiler=false}:{src:string;spoiler?:boolean}){
  const [open,setOpen]=useState(false),[revealed,setRevealed]=useState(!spoiler),[zoom,setZoom]=useState(1),[base,setBase]=useState({width:0,height:0});
  const stage=useRef<HTMLDivElement>(null),image=useRef<HTMLImageElement>(null);
  const measure=useCallback(()=>{const box=stage.current,img=image.current;if(!box||!img||!img.naturalWidth)return;const fit=Math.min(box.clientWidth/img.naturalWidth,box.clientHeight/img.naturalHeight,1);setBase({width:Math.round(img.naturalWidth*fit),height:Math.round(img.naturalHeight*fit)})},[]);
  useEffect(()=>{if(!open)return;setZoom(1);document.documentElement.classList.add("image-preview-open");const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);if(event.key==="0")setZoom(1)},resize=()=>measure();addEventListener("keydown",key);addEventListener("resize",resize);return()=>{document.documentElement.classList.remove("image-preview-open");removeEventListener("keydown",key);removeEventListener("resize",resize)}},[open,measure]);
  useEffect(()=>{if(!open)return;requestAnimationFrame(()=>{const box=stage.current;if(box)box.scrollTo({left:Math.max(0,(box.scrollWidth-box.clientWidth)/2),top:Math.max(0,(box.scrollHeight-box.clientHeight)/2)})})},[zoom,open]);
  const changeZoom=(next:number)=>setZoom(Math.min(5,Math.max(1,Math.round(next*10)/10)));
  const wheel=(event:React.WheelEvent)=>{event.preventDefault();changeZoom(zoom+(event.deltaY<0?.2:-.2))};
  const preview=<div className="image-lightbox" role="dialog" aria-modal="true" aria-label="Image preview" onClick={()=>setOpen(false)}><div className="image-lightbox-toolbar" onClick={event=>event.stopPropagation()}><button title={zoom>1?"Fit image":"Zoom image"} onClick={()=>changeZoom(zoom>1?1:2)}>{zoom>1?<ZoomOut/>:<ZoomIn/>}</button><span className="image-zoom-level">{Math.round(zoom*100)}%</span><a title="Download image" href={src} download="aemeath-image.webp"><Download/></a><button title="Open in new window" onClick={()=>window.open(src,"_blank","noopener,noreferrer")}><ExternalLink/></button><button className="close" title="Close preview" onClick={()=>setOpen(false)}><X/></button></div><div ref={stage} className={`image-lightbox-stage interactive${zoom>1?" zoomed":""}`} onClick={event=>event.stopPropagation()} onWheel={wheel}><img ref={image} src={src} alt="Shared image preview" draggable={false} onLoad={measure} style={base.width?{width:base.width*zoom,height:base.height*zoom}:undefined}/></div></div>;
  return <>{spoiler?<div className="spoiler-preview">{!revealed?<button className="spoiler-image image-preview-trigger" aria-label="Reveal spoiler image" onClick={()=>setRevealed(true)}><img className="chat-image" src={src} alt="Spoiler image" loading="lazy"/><span>SPOILER</span></button>:<><button className="image-preview-trigger" aria-label="Open image preview" onClick={()=>setOpen(true)}><img className="chat-image" src={src} alt="Shared image" loading="lazy"/></button><button className="spoiler-recover" title="Cover spoiler again" aria-label="Cover spoiler again" onClick={()=>setRevealed(false)}><EyeOff size={16}/><span>Cover</span></button></>}</div>:<button className="image-preview-trigger" onClick={()=>setOpen(true)}><img className="chat-image" src={src} alt="Shared image" loading="lazy"/></button>}{open&&typeof document!=="undefined"&&createPortal(preview,document.body)}</>;
}
