"use client";
import {Download,ExternalLink,EyeOff,X,ZoomIn,ZoomOut} from "lucide-react";
import {useCallback,useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";

export default function ImagePreview({src,spoiler=false}:{src:string;spoiler?:boolean}){
  const [open,setOpen]=useState(false),[revealed,setRevealed]=useState(!spoiler),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[base,setBase]=useState({width:0,height:0});
  const stage=useRef<HTMLDivElement>(null),image=useRef<HTMLImageElement>(null),drag=useRef<{id:number;x:number;y:number;panX:number;panY:number}|null>(null);
  const measure=useCallback(()=>{const box=stage.current,img=image.current;if(!box||!img||!img.naturalWidth)return;const fit=Math.min(box.clientWidth/img.naturalWidth,box.clientHeight/img.naturalHeight,1);setBase({width:Math.round(img.naturalWidth*fit),height:Math.round(img.naturalHeight*fit)})},[]);
  useEffect(()=>{if(!open)return;setZoom(1);setPan({x:0,y:0});document.documentElement.classList.add("image-preview-open");const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);if(event.key==="0"){setZoom(1);setPan({x:0,y:0})}},resize=()=>{measure();setPan({x:0,y:0})};addEventListener("keydown",key);addEventListener("resize",resize);return()=>{document.documentElement.classList.remove("image-preview-open");removeEventListener("keydown",key);removeEventListener("resize",resize)}},[open,measure]);
  const clampPan=(value:{x:number;y:number},scale:number)=>{const box=stage.current;if(!box)return value;const maxX=Math.max(0,(base.width*scale-box.clientWidth)/2),maxY=Math.max(0,(base.height*scale-box.clientHeight)/2);return{x:Math.max(-maxX,Math.min(maxX,value.x)),y:Math.max(-maxY,Math.min(maxY,value.y))}};
  const changeZoom=(next:number,nextPan={x:0,y:0})=>{const scale=Math.min(5,Math.max(1,next));setZoom(scale);setPan(scale===1?{x:0,y:0}:clampPan(nextPan,scale))};
  const wheel=(event:React.WheelEvent)=>{event.preventDefault();const box=stage.current;if(!box)return;const scale=Math.min(5,Math.max(1,zoom*Math.exp(-Math.max(-100,Math.min(100,event.deltaY))*.0012))),rect=box.getBoundingClientRect(),pointX=event.clientX-rect.left-box.clientWidth/2,pointY=event.clientY-rect.top-box.clientHeight/2,ratio=scale/zoom;changeZoom(scale,{x:pointX-(pointX-pan.x)*ratio,y:pointY-(pointY-pan.y)*ratio})};
  const pointerDown=(event:React.PointerEvent<HTMLDivElement>)=>{if(zoom<=1||event.button!==0)return;const box=event.currentTarget;drag.current={id:event.pointerId,x:event.clientX,y:event.clientY,panX:pan.x,panY:pan.y};box.setPointerCapture(event.pointerId);box.classList.add("dragging")};
  const pointerMove=(event:React.PointerEvent<HTMLDivElement>)=>{const start=drag.current;if(!start||start.id!==event.pointerId)return;event.preventDefault();setPan(clampPan({x:start.panX+event.clientX-start.x,y:start.panY+event.clientY-start.y},zoom))};
  const pointerEnd=(event:React.PointerEvent<HTMLDivElement>)=>{if(drag.current?.id===event.pointerId)drag.current=null;event.currentTarget.classList.remove("dragging");if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)};
  const preview=<div className="image-lightbox" role="dialog" aria-modal="true" aria-label="Image preview" onClick={()=>setOpen(false)}><div className="image-lightbox-toolbar" onClick={event=>event.stopPropagation()}><button title={zoom>1?"Fit image":"Zoom image"} onClick={()=>changeZoom(zoom>1?1:2)}>{zoom>1?<ZoomOut/>:<ZoomIn/>}</button><span className="image-zoom-level">{Math.round(zoom*100)}%</span><a title="Download image" href={src} download="aemeath-image.webp"><Download/></a><button title="Open in new window" onClick={()=>window.open(src,"_blank","noopener,noreferrer")}><ExternalLink/></button><button className="close" title="Close preview" onClick={()=>setOpen(false)}><X/></button></div><div ref={stage} className={`image-lightbox-stage interactive${zoom>1?" zoomed":""}`} onClick={event=>event.stopPropagation()} onWheel={wheel} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerEnd} onPointerCancel={pointerEnd}><img ref={image} src={src} alt="Shared image preview" draggable={false} onLoad={measure} style={base.width?{width:base.width,height:base.height,transform:`translate3d(${pan.x}px,${pan.y}px,0) scale(${zoom})`}:undefined}/></div></div>;
  return <>{spoiler?<div className="spoiler-preview">{!revealed?<button className="spoiler-image image-preview-trigger" aria-label="Reveal spoiler image" onClick={()=>setRevealed(true)}><img className="chat-image" src={src} alt="Spoiler image" loading="lazy"/><span>SPOILER</span></button>:<><button className="image-preview-trigger" aria-label="Open image preview" onClick={()=>setOpen(true)}><img className="chat-image" src={src} alt="Shared image" loading="lazy"/></button><button className="spoiler-recover" title="Cover spoiler again" aria-label="Cover spoiler again" onClick={()=>setRevealed(false)}><EyeOff size={16}/><span>Cover</span></button></>}</div>:<button className="image-preview-trigger" onClick={()=>setOpen(true)}><img className="chat-image" src={src} alt="Shared image" loading="lazy"/></button>}{open&&typeof document!=="undefined"&&createPortal(preview,document.body)}</>;
}
