"use client";
import {useMemo,useState} from "react";
import {Check,Copy,Crown,ImagePlus,LockKeyhole,Search,ShieldCheck,Trash2,UserMinus,Users,X} from "lucide-react";
type Role="owner"|"admin"|"member";
type Server={id:string;name:string;owner:string;membership_role?:Role;access?:"invite"|"closed";icon?:string;banner?:string;traits?:string};
type Member={id:string;name:string;joined?:number;role?:Role};
const sections=["Server Profile","Members","Roles","Access","Invites"],banners=["#f7edf2","#ff4fa3","#f14458","#f28b36","#f1d34e","#8f45b5","#26aee8","#58d4c7","#5b9f2d","#34363c"];

export default function ServerSettings({server,members,onClose,onSave,onInvite,onManage}:{server:Server;members:Member[];onClose:()=>void;onSave:(value:{name:string;icon:string;banner:string;traits:string[]})=>Promise<void>;onInvite:()=>void;onManage:(value:Record<string,unknown>)=>Promise<void>}){
 const [tab,setTab]=useState("Server Profile"),[name,setName]=useState(server.name),[icon,setIcon]=useState(server.icon||""),[banner,setBanner]=useState(server.banner||"#ff5ca8"),[traits,setTraits]=useState((server.traits||"").split("|").filter(Boolean)),[access,setAccess]=useState<"invite"|"closed">(server.access==="closed"?"closed":"invite"),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
 const owner=server.membership_role==="owner",filtered=useMemo(()=>members.filter(m=>m.name.toLowerCase().includes(query.toLowerCase())),[members,query]);
 async function run(task:()=>Promise<void>){setBusy(true);setError("");try{await task();setSaved(true);setTimeout(()=>setSaved(false),1600)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function image(file?:File){if(!file)return;if(file.size>400000){setError("Choose an image smaller than 400 KB.");return}const reader=new FileReader();reader.onload=()=>setIcon(String(reader.result||""));reader.readAsDataURL(file)}
 return <div className="server-settings-page"><aside className="server-settings-nav"><small>{server.name}</small>{sections.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</aside><main className="server-settings-main"><button className="server-settings-close" aria-label="Close server settings" onClick={onClose}><X/><small>ESC</small></button>
 {tab==="Server Profile"&&<><Heading title="Server Profile" text="Control how this server appears to its members."/><div className="server-profile-grid"><div className="server-profile-form"><label>Server name<input value={name} maxLength={50} onChange={e=>setName(e.target.value)}/></label><div className="settings-separator"/><label>Icon<span className="setting-help">Use a square image under 400 KB.</span><span className="server-icon-actions"><label className="settings-upload"><ImagePlus size={16}/> Change icon<input type="file" accept="image/*" onChange={e=>image(e.target.files?.[0])}/></label>{icon&&<button className="settings-remove" onClick={()=>setIcon("")}><Trash2 size={15}/> Remove</button>}</span></label><div className="settings-separator"/><label>Banner<div className="banner-options">{banners.map(color=><button aria-label={`Use ${color} banner`} className={banner===color?"active":""} style={{background:color}} key={color} onClick={()=>setBanner(color)}/>)}</div></label><div className="settings-separator"/><label>Traits<span className="setting-help">Add up to five interests or qualities.</span><div className="trait-grid">{[0,1,2,3,4].map(i=><input key={i} value={traits[i]||""} placeholder={i===0?"Cozy gaming":"Add a trait"} maxLength={24} onChange={e=>{const next=[...traits];next[i]=e.target.value;setTraits(next)}}/>)}</div></label><Status error={error} saved={saved}/><button className="primary settings-save" disabled={busy||!name.trim()} onClick={()=>void run(()=>onSave({name,icon,banner,traits}))}>{busy?"Saving…":"Save changes"}</button></div><div className="server-card-preview" style={{"--server-banner":banner} as React.CSSProperties}><div className="server-card-banner"/><div className="server-card-icon">{icon?<img src={icon} alt=""/>:name.slice(0,2).toUpperCase()}</div><strong>{name||"Your server"}</strong><span><i/> {members.length} member{members.length===1?"":"s"}</span><div className="server-card-traits">{traits.filter(Boolean).slice(0,3).map(t=><b key={t}>{t}</b>)}</div></div></div></>}
 {tab==="Members"&&<><Heading title="Members" text="Review roles and control who can stay in this server."/><div className="settings-toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search members"/></label><span>{members.length} total</span></div><div className="member-table"><header><span>Member</span><span>Role</span><span>Joined</span><span/></header>{filtered.map(m=><div key={m.id}><span className="member-identity"><i className="avatar">{m.name.slice(0,2).toUpperCase()}</i><strong>{m.name}</strong></span><RoleBadge role={m.role||"member"}/><time>{m.joined?new Date(Number(m.joined)).toLocaleDateString():"—"}</time><span className="member-actions">{m.role!=="owner"&&<>{owner&&<button disabled={busy} onClick={()=>void run(()=>onManage({action:"set-member-role",user:m.id,role:m.role==="admin"?"member":"admin"}))}>{m.role==="admin"?"Remove admin":"Make admin"}</button>}<button className="danger" aria-label={`Remove ${m.name}`} disabled={busy||(!owner&&m.role==="admin")} onClick={()=>void run(()=>onManage({action:"remove-member",user:m.id}))}><UserMinus size={16}/></button></>}</span></div>)}</div><Status error={error} saved={saved}/></>}
 {tab==="Roles"&&<><Heading title="Roles" text="Roles decide who can manage the server and its members."/><div className="role-cards"><RoleCard icon={<Crown/>} title="Owner" count={members.filter(m=>m.role==="owner").length} text="Full control, including assigning administrators. This role cannot be removed."/><RoleCard icon={<ShieldCheck/>} title="Admin" count={members.filter(m=>m.role==="admin").length} text="Can edit the server, create channels and invites, and moderate ordinary members."/><RoleCard icon={<Users/>} title="Member" count={members.filter(m=>!m.role||m.role==="member").length} text="Can read channels, chat, join voice rooms, and stream."/></div><p className="role-note">The owner can assign or remove administrators from the Members page.</p></>}
 {tab==="Access"&&<><Heading title="Access" text="Choose whether invitation links can add new members."/><div className="access-options"><button className={access==="invite"?"active":""} disabled={busy} onClick={()=>void run(async()=>{await onManage({action:"edit-access",access:"invite"});setAccess("invite")})}><ShieldCheck/><strong>Invite only</strong><span>People with a valid seven-day invitation can join.</span></button><button className={access==="closed"?"active":""} disabled={busy} onClick={()=>void run(async()=>{await onManage({action:"edit-access",access:"closed"});setAccess("closed")})}><LockKeyhole/><strong>Closed</strong><span>Existing members keep access. New joins and outstanding invites are disabled.</span></button></div><Status error={error} saved={saved}/></>}
 {tab==="Invites"&&<><Heading title="Invites" text="Create a private link that expires after seven days."/><div className="invite-settings-card"><Copy/><div><strong>Invite someone you trust</strong><p>{access==="closed"?"Open server access before creating a link.":"Anyone with the link can join while access is set to Invite only."}</p></div><button className="primary" disabled={access==="closed"} onClick={onInvite}>Create invite</button></div></>}
 </main></div>
}
function Heading({title,text}:{title:string;text:string}){return <><h1>{title}</h1><p>{text}</p></>}
function Status({error,saved}:{error:string;saved:boolean}){return <>{error&&<p className="account-error">{error}</p>}{saved&&<p className="settings-success"><Check size={15}/> Saved</p>}</>}
function RoleBadge({role}:{role:Role}){return <span className={`role-badge ${role}`}>{role==="owner"?<Crown/>:role==="admin"?<ShieldCheck/>:<Users/>}{role[0].toUpperCase()+role.slice(1)}</span>}
function RoleCard({icon,title,count,text}:{icon:React.ReactNode;title:string;count:number;text:string}){return <article>{icon}<div><strong>{title}</strong><span>{count} member{count===1?"":"s"}</span><p>{text}</p></div></article>}
