"use client";
import { useState } from "react";
import { Check, Copy, ImagePlus, Shield, Trash2, Users, X } from "lucide-react";

type Server={id:string;name:string;owner:string;icon?:string;banner?:string;traits?:string};
type Member={id:string;name:string;joined?:number};
const sections=["Server Profile","Roles","Members","Invites","Access","Integrations","Safety Setup","Audit Log"];
const banners=["#f7edf2","#ff4fa3","#f14458","#f28b36","#f1d34e","#8f45b5","#26aee8","#58d4c7","#5b9f2d","#34363c"];

export default function ServerSettings({server,members,onClose,onSave,onInvite}:{server:Server;members:Member[];onClose:()=>void;onSave:(value:{name:string;icon:string;banner:string;traits:string[]})=>Promise<void>;onInvite:()=>void}){
 const [tab,setTab]=useState("Server Profile"),[name,setName]=useState(server.name),[icon,setIcon]=useState(server.icon||""),[banner,setBanner]=useState(server.banner||"#ff5ca8"),[traits,setTraits]=useState((server.traits||"").split("|").filter(Boolean)),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
 async function save(){setBusy(true);setError("");try{await onSave({name,icon,banner,traits});setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function image(file?:File){if(!file)return;if(file.size>400000){setError("Choose an image smaller than 400 KB.");return}const reader=new FileReader();reader.onload=()=>setIcon(String(reader.result||""));reader.readAsDataURL(file)}
 return <div className="server-settings-page"><aside className="server-settings-nav"><small>{server.name}</small>{sections.map((item)=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</aside><main className="server-settings-main"><button className="server-settings-close" aria-label="Close server settings" onClick={onClose}><X/><small>ESC</small></button>
 {tab==="Server Profile"&&<><h1>Server Profile</h1><p>Customize how your server appears to invited friends.</p><div className="server-profile-grid"><div className="server-profile-form"><label>Server name<input value={name} maxLength={50} onChange={(e)=>setName(e.target.value)}/></label><div className="settings-separator"/><label>Icon<span className="setting-help">Recommended: a square image under 400 KB.</span><span className="server-icon-actions"><label className="settings-upload"><ImagePlus size={16}/> Change server icon<input type="file" accept="image/*" onChange={(e)=>image(e.target.files?.[0])}/></label>{icon&&<button className="settings-remove" onClick={()=>setIcon("")}><Trash2 size={15}/> Remove</button>}</span></label><div className="settings-separator"/><label>Banner<div className="banner-options">{banners.map((color)=><button aria-label={`Use ${color} banner`} className={banner===color?"active":""} style={{background:color}} key={color} onClick={()=>setBanner(color)}/>)}</div></label><div className="settings-separator"/><label>Traits<span className="setting-help">Add up to five interests or qualities.</span><div className="trait-grid">{[0,1,2,3,4].map((i)=><input key={i} value={traits[i]||""} placeholder={i===0?"Cozy gaming":"Add a trait"} maxLength={24} onChange={(e)=>{const next=[...traits];next[i]=e.target.value;setTraits(next)}}/>)}</div></label>{error&&<p className="account-error">{error}</p>}<button className="primary settings-save" disabled={busy||!name.trim()} onClick={save}>{saved?<><Check size={16}/> Saved</>:busy?"Saving…":"Save changes"}</button></div><div className="server-card-preview" style={{"--server-banner":banner} as React.CSSProperties}><div className="server-card-banner"/><div className="server-card-icon">{icon?<img src={icon} alt=""/>:name.slice(0,2).toUpperCase()}</div><strong>{name||"Your server"}</strong><span><i/> {members.length} member{members.length===1?"":"s"}</span>{traits.length>0&&<div className="server-card-traits">{traits.filter(Boolean).slice(0,3).map(t=><b key={t}>{t}</b>)}</div>}</div></div></>}
 {tab==="Members"&&<><h1>Members</h1><p>People who currently have access to this server.</p><div className="settings-list">{members.map((m)=><div key={m.id}><span className="avatar">{m.name.slice(0,2).toUpperCase()}</span><strong>{m.name}</strong>{m.id===server.owner&&<em>Owner</em>}</div>)}</div></>}
 {tab==="Invites"&&<><h1>Invites</h1><p>Create a private link for someone you trust. Links expire after seven days.</p><button className="primary" onClick={onInvite}><Copy size={16}/> Create invite</button></>}
 {tab==="Roles"&&<SettingsInfo icon={<Users/>} title="Roles" text="Aemeath currently uses two clear roles: server owner and member. The owner manages the server, channels, and invites."/>}
 {tab==="Access"&&<SettingsInfo icon={<Shield/>} title="Access" text="This server is private. Only signed-in people with a valid invite can join and read its channels."/>}
 {tab==="Integrations"&&<SettingsInfo title="Integrations" text="Integrations will appear here when they are connected to your server."/>}
 {tab==="Safety Setup"&&<SettingsInfo icon={<Shield/>} title="Safety Setup" text="Private membership, authenticated messages, and owner-only management are enabled for this server."/>}
 {tab==="Audit Log"&&<SettingsInfo title="Audit Log" text="Server management activity will be listed here as Aemeath adds more moderation controls."/>}
 </main></div>
}
function SettingsInfo({icon,title,text}:{icon?:React.ReactNode;title:string;text:string}){return <div className="settings-info">{icon}<h1>{title}</h1><p>{text}</p></div>}
