import {randomBytes} from 'node:crypto';
import {database} from '@/db/raw';
import {AppError,json,failure,input,str,hashPassword,verifyPassword,getAccount,requireAccount,sessionHash,startSession,sessionCookie,throttle,validateAccount} from '@/lib/server/auth';
export const dynamic='force-dynamic';
export async function GET(r:Request){try{const username=new URL(r.url).searchParams.get('username');if(username!==null){if(!/^[A-Za-z0-9_]{3,24}$/.test(username))return json({available:false});const me=await getAccount();const a=await database().prepare('SELECT id FROM accounts WHERE username_key=?').bind(username.toLowerCase()).first<{id:string}>();return json({available:!a||a.id===me?.id});}return json({user:await getAccount()});}catch(e){return failure(e)}}
export async function POST(r:Request){try{const d=await input(r);const db=database();const action=d.action;const ip=r.headers.get('cf-connecting-ip')||'local';
if(action==='logout'){const hash=await sessionHash();if(hash)await db.prepare('DELETE FROM auth_sessions WHERE hash=?').bind(hash).run();return json({ok:true},200,{'Set-Cookie':sessionCookie('',r,true)});}
if(action==='register'){await throttle('register:'+ip,10);const name=str(d.username).trim(),email=str(d.email).trim(),password=str(d.password);validateAccount(name,email,password);const existing=await db.prepare('SELECT username_key FROM accounts WHERE username_key=? OR email_key=?').bind(name.toLowerCase(),email.toLowerCase()).first<{username_key:string}>();if(existing)throw new AppError(existing.username_key===name.toLowerCase()?'That username already exists.':'That email already has an account.',409);const salt=randomBytes(24).toString('hex');const hash=await hashPassword(password,salt);const id=crypto.randomUUID();try{await db.batch([db.prepare('INSERT INTO accounts (id,username,username_key,email,email_key,salt,password_hash,created) VALUES (?,?,?,?,?,?,?,?)').bind(id,name,name.toLowerCase(),email,email.toLowerCase(),salt,hash,Date.now()),db.prepare('INSERT INTO profiles (id,name) VALUES (?,?)').bind(id,name)]);}catch(e){if(String(e).includes('UNIQUE'))throw new AppError('That username or email already exists.',409);throw e;}const token=await startSession(id);return json({user:{id,name,email}},201,{'Set-Cookie':sessionCookie(token,r)});}
if(action==='login'){const identity=str(d.identifier).trim().toLowerCase(),password=str(d.password);if(!identity||!password||password.length>128)throw new AppError('Enter your username or email and password.');await throttle('login-ip:'+ip,50);await throttle('login-account:'+identity,12);const a=await db.prepare('SELECT * FROM accounts WHERE username_key=? OR email_key=?').bind(identity,identity).first<{id:string;username:string;email:string;salt:string;password_hash:string}>();const valid=await verifyPassword(password,a?.salt||'000000000000000000000000000000000000000000000000',a?.password_hash||'0'.repeat(64));if(!a||!valid)throw new AppError('Incorrect username, email, or password.',401);const token=await startSession(a.id);return json({user:{id:a.id,name:a.username,email:a.email}},200,{'Set-Cookie':sessionCookie(token,r)});}
if(action==='update'){const me=await requireAccount();await throttle('update:'+me.id,12);const name=str(d.username).trim(),email=str(d.email).trim(),password=str(d.currentPassword),newPassword=str(d.newPassword);validateAccount(name,email,newPassword||undefined);const a=await db.prepare('SELECT salt,password_hash FROM accounts WHERE id=?').bind(me.id).first<{salt:string;password_hash:string}>();if(!a||!password||password.length>128||!await verifyPassword(password,a.salt,a.password_hash))throw new AppError('Your current password is incorrect.',403);const other=await db.prepare('SELECT id FROM accounts WHERE (username_key=? OR email_key=?) AND id<>?').bind(name.toLowerCase(),email.toLowerCase(),me.id).first();if(other)throw new AppError('That username or email already exists.',409);const salt=newPassword?randomBytes(24).toString('hex'):a.salt;const hash=newPassword?await hashPassword(newPassword,salt):a.password_hash;try{const result=await db.prepare('UPDATE accounts SET username=?,username_key=?,email=?,email_key=?,salt=?,password_hash=? WHERE id=? AND password_hash=?').bind(name,name.toLowerCase(),email,email.toLowerCase(),salt,hash,me.id,a.password_hash).run();if(!result.meta.changes)throw new AppError('Your account changed. Please log in again.',409);await db.prepare('UPDATE profiles SET name=? WHERE id=?').bind(name,me.id).run();}catch(e){if(String(e).includes('UNIQUE'))throw new AppError('That username or email already exists.',409);throw e;}let token:string|undefined;if(newPassword){await db.prepare('DELETE FROM auth_sessions WHERE user=?').bind(me.id).run();token=await startSession(me.id);}return json({user:{id:me.id,name,email}},200,token?{'Set-Cookie':sessionCookie(token,r)}:{});}
throw new AppError('Unknown action.');}catch(e){return failure(e)}}
