import {sqliteTable,text,integer,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),name:text('name').notNull()});
export const servers=sqliteTable('servers',{id:text('id').primaryKey(),name:text('name').notNull(),owner:text('owner').notNull(),created:integer('created').notNull()});
export const members=sqliteTable('members',{server:text('server').notNull().references(()=>servers.id),user:text('user').notNull(),joined:integer('joined').notNull()},t=>[primaryKey({columns:[t.server,t.user]}),index('idx_members_user').on(t.user)]);
export const channels=sqliteTable('channels',{id:text('id').primaryKey(),server:text('server').notNull().references(()=>servers.id),name:text('name').notNull(),created:integer('created').notNull()},t=>[index('idx_channels_server').on(t.server)]);
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),channel:text('channel').notNull().references(()=>channels.id),user:text('user').notNull(),body:text('body').notNull(),created:integer('created').notNull()},t=>[index('idx_messages_channel_created').on(t.channel,t.created)]);
export const invites=sqliteTable('invites',{code:text('code').primaryKey(),server:text('server').notNull().references(()=>servers.id),expires:integer('expires').notNull()});

export const accounts=sqliteTable('accounts',{id:text('id').primaryKey(),username:text('username').notNull(),usernameKey:text('username_key').notNull().unique(),email:text('email').notNull(),emailKey:text('email_key').notNull().unique(),salt:text('salt').notNull(),passwordHash:text('password_hash').notNull(),created:integer('created').notNull()});
export const authSessions=sqliteTable('auth_sessions',{hash:text('hash').primaryKey(),user:text('user').notNull().references(()=>accounts.id),expires:integer('expires').notNull()},t=>[index('idx_auth_sessions_user').on(t.user)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),hits:integer('hits').notNull(),expires:integer('expires').notNull()});
export const conversations=sqliteTable('conversations',{id:text('id').primaryKey(),first:text('first').notNull().references(()=>accounts.id),second:text('second').notNull().references(()=>accounts.id),created:integer('created').notNull(),updated:integer('updated').notNull(),pair:text('pair').notNull().unique()},t=>[index('idx_conversations_first').on(t.first),index('idx_conversations_second').on(t.second)]);
export const directMessages=sqliteTable('direct_messages',{id:text('id').primaryKey(),conversation:text('conversation').notNull().references(()=>conversations.id),sender:text('sender').notNull().references(()=>accounts.id),body:text('body').notNull(),created:integer('created').notNull()},t=>[index('idx_dm_conversation_created').on(t.conversation,t.created)]);
export const calls=sqliteTable('calls',{id:text('id').primaryKey(),conversation:text('conversation').notNull().references(()=>conversations.id),caller:text('caller').notNull(),callee:text('callee').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),offer:text('offer'),answer:text('answer'),created:integer('created').notNull(),updated:integer('updated').notNull(),callerSeen:integer('caller_seen').notNull(),calleeSeen:integer('callee_seen').notNull(),reason:text('reason')},t=>[index('idx_calls_callee_status').on(t.callee,t.status)]);
export const callLocks=sqliteTable('call_locks',{user:text('user').primaryKey(),call:text('call').notNull(),expires:integer('expires').notNull()});
